=== maiteuu/T4E3ML/Web orria - ZAHARRA/xml/federazioa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Federazioa">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="TaldeGuztiak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Talde" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Izena" type="xs:string" />
                                        <xs:element name="Hiria" type="xs:string" />
                                        <xs:element name="Ezkutua" type="xs:string" />
                                        <xs:element name="Jokalariak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Jokalari" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Izena" type="xs:string" />
                                                                <xs:element name="Abizena" type="xs:string" />
                                                                <xs:element name="Posizioa" type="xs:string" />
                                                            </xs:sequence>
                                                            <xs:attribute name="dortsala" type="xs:integer" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Denboraldiak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Denboraldia" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        
                                        <xs:element name="DenboraldikoTaldeak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Talde" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Izena" type="xs:string" />
                                                                <xs:element name="Hiria" type="xs:string" />
                                                                <xs:element name="Ezkutua" type="xs:string" />
                                                                <xs:element name="Puntuak" type="xs:integer" minOccurs="0" />
                                                                <xs:element name="Jokalariak">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="Jokalari" minOccurs="0" maxOccurs="unbounded">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="Izena" type="xs:string" />
                                                                                        <xs:element name="Abizena" type="xs:string" />
                                                                                        <xs:element name="Posizioa" type="xs:string" />
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="dortsala" type="xs:integer" use="required" />
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="Sailkapena" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Lerroa" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Posizioa" type="xs:integer"/>
                                                                <xs:element name="Taldea" type="xs:string"/>
                                                                <xs:element name="Ezkutua" type="xs:string"/>
                                                                <xs:element name="Puntuak" type="xs:integer"/>
                                                                <xs:element name="Jokatuak" type="xs:integer"/>
                                                                <xs:element name="Irabaziak" type="xs:integer"/>
                                                                <xs:element name="Berdinduak" type="xs:integer"/>
                                                                <xs:element name="Galduak" type="xs:integer"/>
                                                                <xs:element name="AldekoGolak" type="xs:integer"/>
                                                                <xs:element name="AurkakoGolak" type="xs:integer"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="Jardunaldiak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Jardunaldi" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Partidua" minOccurs="0" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="EtxekoTaldea" type="xs:string" />
                                                                            <xs:element name="EtxekoEzkutua" type="xs:string" />
                                                                            <xs:element name="KanpokoTaldea" type="xs:string" />
                                                                            <xs:element name="KanpokoEzkutua" type="xs:string" />
                                                                            
                                                                            <xs:element name="Emaitza" minOccurs="0">
                                                                                <xs:complexType>
                                                                                    <xs:attribute name="etxekoGolak" type="xs:integer" use="required"/>
                                                                                    <xs:attribute name="kanpokoGolak" type="xs:integer" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>

                                                                        </xs:sequence>
                                                                        <xs:attribute name="egoera" type="xs:string" use="optional" />
                                                                        <xs:attribute name="id" type="xs:integer" use="required" />
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="zenbakia" type="xs:integer" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>
                                    <xs:attribute name="urtea" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== maiteuu/T4E3ML/Web orria - ZAHARRA/xml/federazioa.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Federazioa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="federazioa.xsd">
    <TaldeGuztiak>
        <Talde>
            <Izena>Barça Futsal</Izena>
            <Hiria>Barcelona</Hiria>
            <Ezkutua>barcelona</Ezkutua>
            <Jokalariak>
                <Jokalari dortsala="8">
                    <Izena>Adolfo</Izena>
                    <Abizena>Fernández</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="21">
                    <Izena>Dídac</Izena>
                    <Abizena>Plana</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="3">
                    <Izena>Matheus</Izena>
                    <Abizena>Rodrigues</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="26">
                    <Izena>Miquel</Izena>
                    <Abizena>Feixas</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="2">
                    <Izena>Antonio</Izena>
                    <Abizena>Pérez</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="4">
                    <Izena>André</Izena>
                    <Abizena>Coelho</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="11">
                    <Izena>Alex</Izena>
                    <Abizena>Yepes</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="99">
                    <Izena>Erick</Izena>
                    <Abizena>Mendonça</Abizena>
                    <Posizioa>Unibertsala</Posizioa>
                </Jokalari>
            </Jokalariak>
        </Talde>
        <Talde>
            <Izena>ElPozo Murcia</Izena>
            <Hiria>Murcia</Hiria>
            <Ezkutua>elpozo</Ezkutua>
            <Jokalariak>
                <Jokalari dortsala="11">
                    <Izena>Rafa</Izena>
                    <Abizena>Santos</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="5">
                    <Izena>Felipe</Izena>
                    <Abizena>Valerio</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="13">
                    <Izena>Gadeia</Izena>
                    <Abizena>Fabricio</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="12">
                    <Izena>Juanjo</Izena>
                    <Abizena>Angosto</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="10">
                    <Izena>Marcel</Izena>
                    <Abizena>Marques</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="1">
                    <Izena>Edu</Izena>
                    <Abizena>Sousa</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="9">
                    <Izena>Bruno</Izena>
                    <Abizena>Taffy</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="96">
                    <Izena>Artem</Izena>
                    <Abizena>Niyazov</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="8">
                    <Izena>David</Izena>
                    <Abizena>Álvarez</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="4">
                    <Izena>Ricardo</Izena>
                    <Abizena>Mayor</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="9">
                    <Izena>Sergio</Izena>
                    <Abizena>Lozano</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="10">
                    <Izena>Jean Pierre</Izena>
                    <Abizena>Pito</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
            </Jokalariak>
        </Talde>
        <Talde>
            <Izena>Inter Movistar</Izena>
            <Hiria>Torrejon</Hiria>
            <Ezkutua>inter</Ezkutua>
            <Jokalariak>
                <Jokalari dortsala="1">
                    <Izena>Jesús</Izena>
                    <Abizena>Herrero</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="8">
                    <Izena>Raúl</Izena>
                    <Abizena>Gómez</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="2">
                    <Izena>Cecilio</Izena>
                    <Abizena>Morales</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="3">
                    <Izena>Lucas</Izena>
                    <Abizena>Tripodi</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="12">
                    <Izena>Fits</Izena>
                    <Abizena>Rafael</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="6">
                    <Izena>Javi</Izena>
                    <Abizena>Mínguez</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="10">
                    <Izena>Tomás</Izena>
                    <Abizena>Drahovsky</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="14">
                    <Izena>Jhonatan</Izena>
                    <Abizena>Linhares</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="7">
                    <Izena>Humberto</Izena>
                    <Abizena>Dalmata</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="19">
                    <Izena>Kaito</Izena>
                    <Abizena>Yamada</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
            </Jokalariak>
        </Talde>
        <Talde>
            <Izena>Mallorca Palma Futsal</Izena>
            <Hiria>Palma</Hiria>
            <Ezkutua>baleares</Ezkutua>
            <Jokalariak>
                <Jokalari dortsala="1">
                    <Izena>Luan</Izena>
                    <Abizena>Muller</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="10">
                    <Izena>Cleber</Izena>
                    <Abizena>Gomes</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="8">
                    <Izena>Mario</Izena>
                    <Abizena>Rivillos</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="9">
                    <Izena>Moslem</Izena>
                    <Abizena>Oladghobad</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="11">
                    <Izena>Bruno</Izena>
                    <Abizena>Gomes</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="21">
                    <Izena>Carlos</Izena>
                    <Abizena>Barrón</Abizena>
                    <Posizioa>Atezaina</Posizioa>
                </Jokalari>
                <Jokalari dortsala="15">
                    <Izena>Hossein</Izena>
                    <Abizena>Tayebi</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="2">
                    <Izena>Chaguinha</Izena>
                    <Abizena>Bruno</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
                <Jokalari dortsala="17">
                    <Izena>Fabinho</Izena>
                    <Abizena>Teixeira</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
                <Jokalari dortsala="5">
                    <Izena>Rómulo</Izena>
                    <Abizena>Alves</Abizena>
                    <Posizioa>Itxiera</Posizioa>
                </Jokalari>
            </Jokalariak>
        </Talde>
        <Talde>
            <Izena>Jaén Paraíso Interior</Izena>
            <Hiria>Jaen</Hiria>
            <Ezkutua>jaen</Ezkutua>
            <Jokalariak>
                <Jokalari dortsala="10">
                    <Izena>Alan</Izena>
                    <Abizena>Brandi</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="41">
                    <Izena>Mati</Izena>
                    <Abizena>Rosa</Abizena>
                    <Posizioa>Pibota</Posizioa>
                </Jokalari>
                <Jokalari dortsala="20">
                    <Izena>Chino</Izena>
                    <Abizena>Javier</Abizena>
                    <Posizioa>Hegala</Posizioa>
                </Jokalari>
